services:
  postgres:
    image: postgres:15
    container_name: rss_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rss_user
      POSTGRES_PASSWORD: rss_password
      POSTGRES_DB: rss_feed
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initialisation:/docker-entrypoint-initdb.d

  rss_parser:
    build: 
      context: .
      dockerfile: Dockerfile.db
    container_name: rss_parser
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_HOST: "postgres"
      DB_NAME: "rss_feed"
      DB_USER: "rss_user"
      DB_PASSWORD: "rss_password"
  web:
    build: 
      context: .
      dockerfile: Dockerfile.app
    container_name: rss_web
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: rss_feed
      DB_USER: rss_user
      DB_PASSWORD: rss_password
    ports:
      - "8000:8000"
volumes:
  postgres_data: